# Generated by Django 5.2.8 on 2025-11-28 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_message_options_message_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Chat session this message belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.chatsession'),
        ),
    ]
