# Generated by Django 5.2.8 on 2025-12-01 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_chatsession_message_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('chat', 'Chat'), ('document', 'Document'), ('manual', 'Manual')], default='chat', help_text='Where this memory came from.', max_length=20)),
                ('title', models.CharField(blank=True, help_text='Optional short label for the memory.', max_length=255)),
                ('content', models.TextField(help_text='The remembered fact, summary, preference, or detail about the user.')),
                ('importance', models.IntegerField(default=0, help_text='A simple integer importance score. Higher values indicate the memory is more important and should be preferred when selecting context.')),
                ('is_active', models.BooleanField(default=True, help_text='Soft‑delete flag; inactive memories are ignored in retrieval.')),
                ('embedding', models.JSONField(blank=True, help_text='Vector embedding of the memory content for semantic search.', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, help_text='User this memory belongs to; null when anonymous.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memories', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, help_text='Optional chat session that produced this memory.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memories', to='api.chatsession')),
            ],
            options={
                'ordering': ['-importance', '-updated'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Plain text content of the professional document (CV, notes, etc.).')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('embedding', models.JSONField(blank=True, help_text='Vector embedding of the content for semantic search.', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Optional extra metadata such as tags, skills, experience level.')),
                ('owner', models.ForeignKey(blank=True, help_text='Optional owner of the document; null for anonymous usage.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professional_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
