# Generated by Django 5.2.8 on 2025-12-02 08:27

"""
Migration to convert embedding fields from JSONField to pgvector VectorField.

Instead of attempting to cast jsonb -> vector (which fails), we drop the old
columns and recreate them as vector columns. This is safe because embeddings
are always recomputed by the backend (for documents and memories) and do not
need to be preserved across the migration.
"""

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_memoryentry_professionaldocument"),
    ]

    operations = [
        # Drop old JSONB-based embedding columns
        migrations.RemoveField(
            model_name="memoryentry",
            name="embedding",
        ),
        migrations.RemoveField(
            model_name="professionaldocument",
            name="embedding",
        ),
        # Recreate them as pgvector fields
        migrations.AddField(
            model_name="memoryentry",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=1536,
                null=True,
                help_text="Vector embedding of the memory content for semantic search.",
            ),
        ),
        migrations.AddField(
            model_name="professionaldocument",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=1536,
                null=True,
                help_text="Vector embedding of the content for semantic search.",
            ),
        ),
    ]
