"""
Django settings for assistant project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from a .env file located in the backend root
# (i.e. the folder that contains manage.py).
env_path = BASE_DIR / ".env"
load_dotenv(env_path)

def get_env_setting(name: str, default=None, required: bool = False):
    """
    Helper to fetch environment variables.
    If required=True and the variable is missing, raise ImproperlyConfigured.
    """
    value = os.getenv(name, default)
    if required and value is None:
        raise ImproperlyConfigured(f"Missing required environment variable: {name}")
    return value


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_env_setting("DJANGO_SECRET_KEY", required=True)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_env_setting("DJANGO_DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = get_env_setting(
    "DJANGO_ALLOWED_HOSTS",
    "localhost,127.0.0.1",
).split(",")

# CORS configuration – only allow explicitly configured frontend origins.
# Defaults cover common dev ports for React/Vite and Next.js.
CORS_ALLOWED_ORIGINS = get_env_setting(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:3000,http://127.0.0.1:3000,http://localhost:5173,http://127.0.0.1:5173",
).split(",")

# OpenAI API key loaded from environment
OPENAI_API_KEY = get_env_setting("OPENAI_API_KEY", default=None, required=False)


# Application definition

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "pgvector.django",
    "rest_framework",
    "corsheaders",
    "api.apps.ApiConfig",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # must be high in the list
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'assistant.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'assistant.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# Configure PostgreSQL via environment variables:
#   POSTGRES_DB
#   POSTGRES_USER
#   POSTGRES_PASSWORD
#   POSTGRES_HOST  (default: localhost)
#   POSTGRES_PORT  (default: 5432)
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": get_env_setting("POSTGRES_DB", "assistant"),
        "USER": get_env_setting("POSTGRES_USER", "assistant"),
        "PASSWORD": get_env_setting("POSTGRES_PASSWORD", ""),
        "HOST": get_env_setting("POSTGRES_HOST", "localhost"),
        "PORT": get_env_setting("POSTGRES_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Embedding configuration (used by the memory/embedding utilities)
EMBEDDING_MODEL_NAME = get_env_setting(
    "EMBEDDING_MODEL_NAME", "text-embedding-3-small"
)
EMBEDDING_DIMENSIONS = int(get_env_setting("EMBEDDING_DIMENSIONS", "1536"))

# Chat model configuration (used by the OpenAI chat completion calls)
CHAT_MODEL_NAME = get_env_setting("CHAT_MODEL_NAME", "gpt-4o-mini")
